### ISSUE TITLE
Options: Calling delete_option() before adding any options causes an error

### ISSUE THREAD

**Issue by atanas-dev** [Automattic/wordbless#16]
#### Steps to reproduce the issue

1. Create a test containing this:
```php
public function test_delete_option() {
	delete_option( 'foo' );
	$this->assertTrue( true );
}
```
2. Make sure this is the first (or only) test you run

#### What I expected
No errors when running the test. 

#### What happened instead
```
1) [TEST_CLASS]::test_delete_option
array_keys() expects parameter 1 to be array, null given

[PROJECT_DIR]/vendor/automattic/wordbless/src/Options.php:121
[PROJECT_DIR]/vendor/automattic/wordbless/src/Options.php:109
[PROJECT_DIR]/wordpress/wp-includes/class-wp-hook.php:287
[PROJECT_DIR]/wordpress/wp-includes/class-wp-hook.php:311
[PROJECT_DIR]/wordpress/wp-includes/plugin.php:478
[PROJECT_DIR]/wordpress/wp-includes/option.php:699
[PROJECT_DIR]/tests/php/test-class.php:29
```

The culprit seems to be this:
```php
public function clear_cache_group() {
	global $wp_object_cache;

	foreach ( array_keys( $wp_object_cache->cache['options'] ) as $key ) {
		wp_cache_delete( $key, 'options' );
	}
}
```
Since no option has been set before `$wp_object_cache->cache['options']` ends up being null.

**Comment by leogermani** [comment]
@atanas-dev thanks for the detailed report!

https://github.com/Automattic/wordbless/pull/17 should fix it!

**Comment by szepeviktor** [comment]
What a great CI we have here sheltering us from any malfunction!

**Comment by leogermani** [comment]
@szepeviktor I was going to ask you why I was not seeing any CI stuff on the PR footer

**Comment by szepeviktor** [comment]
@leogermani 

![2020-08-26_20-51-47](https://user-images.githubusercontent.com/952007/91344341-1c31c080-e7de-11ea-8b5e-e984ac8242b1.gif)
