### ISSUE TITLE
Use Yoast Polyfill?

### ISSUE THREAD

**Issue by kraftbj** [Automattic/wordbless#52]
When we extend using WorDBless as the base test class, we run into issues where we can't use `SetupBeforeClass` in a situation where we need cross-compat between various versions of PHP.

Yoast provides a polyfill, but I don't believe we use both at the same time. Would this be something WorDBless could/should do?

e.g. https://github.com/Yoast/PHPUnit-Polyfills#testcases

**Comment by szepeviktor** [comment]
> we run into issues

Can be read here https://github.com/Automattic/jetpack/pull/23687#discussion_r838830829
